# Generated by Django 3.2.9 on 2021-12-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_history_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='name',
        ),
    ]
